#!/bin/bash

# project path
POCKET_DOCKER_HOME="/drives/c/Users/jakub.bigolas/OneDrive/PocketDocker"

# import config file
. "$POCKET_DOCKER_HOME/config/config.sh"

# import and start engine
. "$POCKET_DOCKER_HOME/engine/engine-embed.sh"
engineCreateContext "$POCKET_DOCKER_HOME"
engineStart         "$POCKET_DOCKER_HOME" "$@"
